[book]
authors = ["Kurt Pan"]
language = "en"
multilingual = false
src = "src"
title = "拟人化"

[preprocessor.katex]
after = ["links"]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
marker = "[TOC]"
max-level = 4

[output.html]
[output.html.print]
enable = true

[output.pdf]
chrome = "/opt/homebrew/bin/chromium"
